package dev.hermes.tooling.launch;

import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.OutputStreamWriter;
import java.nio.charset.StandardCharsets;
import java.util.Map;
import java.util.Properties;

public final class RuntimeConfigWriter {

    private RuntimeConfigWriter() {}

    public static void write(File outputDir, Map<String, String> properties) throws IOException {
        if (!outputDir.exists() && !outputDir.mkdirs()) {
            throw new IOException("Could not create " + outputDir.getAbsolutePath());
        }
        Properties props = new Properties();
        for (Map.Entry<String, String> entry : properties.entrySet()) {
            props.setProperty(entry.getKey(), entry.getValue());
        }
        File file = new File(outputDir, "hermes-runtime.properties");
        try (OutputStreamWriter writer =
                     new OutputStreamWriter(new FileOutputStream(file), StandardCharsets.UTF_8)) {
            props.store(writer, "Generated by Hermes LaunchConfigResolver");
        }
    }
}
