package dev.hermes.gradle.html;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;

/** Writes the TeaVM HTML main class that instantiates the game without {@code Class.forName}. */
public final class TeaLauncherGenerator {

  private TeaLauncherGenerator() {}

  public static void write(Path outputDirectory, String applicationClass) throws IOException {
    int lastDot = applicationClass.lastIndexOf('.');
    if (lastDot < 1) {
      throw new IllegalArgumentException("Invalid application class name: " + applicationClass);
    }
    String simpleName = applicationClass.substring(lastDot + 1);

    Path packageDir = outputDirectory.resolve("dev/hermes/launcher/html/generated");
    Files.createDirectories(packageDir);
    Path file = packageDir.resolve("GeneratedTeaVMLauncher.java");

    String source =
        "package dev.hermes.launcher.html.generated;\n"
            + "\n"
            + "import com.github.xpenatan.gdx.teavm.backends.web.WebApplication;\n"
            + "import com.github.xpenatan.gdx.teavm.backends.web.WebApplicationConfiguration;\n"
            + "import dev.hermes.core.HermesGdxApplication;\n"
            + "import "
            + applicationClass
            + ";\n"
            + "\n"
            + "/** Generated by the Hermes Gradle plugin; do not edit. */\n"
            + "public final class GeneratedTeaVMLauncher {\n"
            + "\n"
            + "  private GeneratedTeaVMLauncher() {}\n"
            + "\n"
            + "  public static void main(String[] args) {\n"
            + "    WebApplicationConfiguration config = new WebApplicationConfiguration(\"canvas\");\n"
            + "    config.width = 0;\n"
            + "    config.height = 0;\n"
            + "    new WebApplication(new HermesGdxApplication(new "
            + simpleName
            + "()), config);\n"
            + "  }\n"
            + "}\n";

    Files.writeString(file, source, StandardCharsets.UTF_8);
  }
}
