package dev.hermes.gradle.internal;

import dev.hermes.gradle.internal.HermesGameConfigs;
import dev.hermes.gradle.internal.HermesPlatforms;
import dev.hermes.gradle.dsl.HermesExtension;
import dev.hermes.tooling.config.HermesGameConfig;
import dev.hermes.tooling.launch.HermesLaunchProperties;
import dev.hermes.tooling.platform.DesktopPlatform;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.OutputStreamWriter;
import java.nio.charset.StandardCharsets;
import java.util.Properties;
import org.gradle.api.GradleException;
import org.gradle.api.Project;

/** Writes {@code hermes-runtime.properties} for packaged runtime configuration. */
public final class HermesRuntimeConfigGenerator {

  private HermesRuntimeConfigGenerator() {}

  public static void write(Project gameProject, HermesExtension extension, File outputDir) {
    HermesGameConfig gameConfig = HermesGameConfigs.parse(gameProject);
    DesktopPlatform desktop = HermesPlatforms.resolve(gameProject).getDesktop();

    if (!outputDir.exists() && !outputDir.mkdirs()) {
      throw new GradleException("Could not create " + outputDir.getAbsolutePath());
    }

    boolean debug =
        HermesDistributionMode.isDistributionExport(gameProject) ? false : extension.isDebug();
    Properties properties = new Properties();
    HermesLaunchProperties.builder()
        .applicationClass(extension.getApplicationClass())
        .debug(debug)
        .windowTitle(gameConfig.getTitle())
        .windowSize(desktop.getWidth(), desktop.getHeight())
        .scene(gameConfig.getScene())
        .renderPipeline(gameConfig.getRenderPipeline())
        .desktopVsync(desktop.isVsync())
        .desktopResizable(desktop.isResizable())
        .desktopForegroundFps(desktop.getForegroundFps())
        .build()
        .applyTo(properties);

    File file = new File(outputDir, "hermes-runtime.properties");
    try (OutputStreamWriter writer =
        new OutputStreamWriter(new FileOutputStream(file), StandardCharsets.UTF_8)) {
      properties.store(writer, "Generated by Hermes Gradle plugin");
    } catch (IOException e) {
      throw new GradleException("Failed to write hermes-runtime.properties", e);
    }
  }
}
