package dev.hermes.launcher.html;

import com.github.xpenatan.gdx.teavm.backends.shared.config.AssetFileHandle;
import com.github.xpenatan.gdx.teavm.backends.shared.config.compiler.TeaCompiler;
import com.github.xpenatan.gdx.teavm.backends.web.config.backend.WebBackend;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.OutputStreamWriter;
import java.nio.charset.StandardCharsets;
import java.util.Properties;
import org.teavm.tooling.TeaVMSourceFilePolicy;
import org.teavm.tooling.sources.DirectorySourceFileProvider;
import org.teavm.vm.TeaVMOptimizationLevel;

/** Builds the TeaVM/HTML application. */
public final class TeaVMBuilder {

  private TeaVMBuilder() {}

  public static void main(String[] args) throws IOException {
    boolean debug = Boolean.parseBoolean(System.getProperty("hermes.debug", "false"));
    boolean startJetty = false;
    for (String arg : args) {
      if ("debug".equals(arg)) {
        debug = true;
      } else if ("run".equals(arg)) {
        startJetty = true;
      }
    }

    String applicationClass = System.getProperty("hermes.applicationClass");
    if (applicationClass == null || applicationClass.isBlank()) {
      throw new IllegalStateException(
          "hermes.applicationClass system property is required (set by :game:hermesRunHtml).");
    }

    String title = System.getProperty("hermes.window.title", "Hermes");
    int width = Integer.parseInt(System.getProperty("hermes.window.width", "640"));
    int height = Integer.parseInt(System.getProperty("hermes.window.height", "480"));
    String gameName = System.getProperty("hermes.game.name", "HermesGame");
    String gameScene = System.getProperty("hermes.game.scene", "scenes/main.json");

    File runtimeConfigDir = new File("build/hermes-runtime");
    writeRuntimeProperties(
        runtimeConfigDir, applicationClass, debug, title, width, height, gameName, gameScene);

    File gameSources = new File("../game/src/main/java");
    File apiSources = new File("../hermes-api/src/main/java");
    File coreSources = new File("../hermes-core/src/main/java");
    File launcherSources = new File("src/main/java");
    TeaCompiler compiler =
        new TeaCompiler(
                new WebBackend()
                    .setHtmlWidth(width)
                    .setHtmlHeight(height)
                    .setHtmlTitle(title)
                    .setWebAssembly(true)
                    .setStartJettyAfterBuild(startJetty)
                    .setJettyPort(8080))
            .addAssets(new AssetFileHandle("../assets"))
            .addAssets(new AssetFileHandle(runtimeConfigDir.getPath()))
            .setOptimizationLevel(debug ? TeaVMOptimizationLevel.SIMPLE : TeaVMOptimizationLevel.ADVANCED)
            .setMainClass("dev.hermes.launcher.html.generated.GeneratedTeaVMLauncher")
            .setObfuscated(!debug)
            .setDebugInformationGenerated(debug)
            .setSourceMapsFileGenerated(debug)
            .setSourceFilePolicy(TeaVMSourceFilePolicy.COPY)
            .addSourceFileProvider(new DirectorySourceFileProvider(launcherSources))
            .addSourceFileProvider(new DirectorySourceFileProvider(gameSources))
            .addSourceFileProvider(new DirectorySourceFileProvider(coreSources))
            .addSourceFileProvider(new DirectorySourceFileProvider(apiSources));

    compiler.build(new File("build/dist"));
  }

  private static void writeRuntimeProperties(
      File dir,
      String applicationClass,
      boolean debug,
      String title,
      int width,
      int height,
      String gameName,
      String gameScene)
      throws IOException {
    if (!dir.exists() && !dir.mkdirs()) {
      throw new IOException("Could not create " + dir.getAbsolutePath());
    }
    Properties properties = new Properties();
    properties.setProperty("hermes.applicationClass", applicationClass);
    properties.setProperty("hermes.debug", Boolean.toString(debug));
    properties.setProperty("hermes.window.title", title);
    properties.setProperty("hermes.window.width", Integer.toString(width));
    properties.setProperty("hermes.window.height", Integer.toString(height));
    properties.setProperty("hermes.game.name", gameName);
    properties.setProperty("hermes.game.scene", gameScene);
    File file = new File(dir, "hermes-runtime.properties");
    try (OutputStreamWriter writer = new OutputStreamWriter(new FileOutputStream(file), StandardCharsets.UTF_8)) {
      properties.store(writer, "Generated by TeaVMBuilder for HTML/WASM runtime");
    }
  }
}
