package dev.hermes.gradle;

import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.OutputStreamWriter;
import java.nio.charset.StandardCharsets;
import java.util.Properties;
import org.gradle.api.GradleException;
import org.gradle.api.Project;

/** Writes {@code hermes-runtime.properties} for packaged runtime configuration. */
final class HermesRuntimeConfigGenerator {

  private HermesRuntimeConfigGenerator() {}

  static void write(Project gameProject, HermesExtension extension, File outputDir) {
    HermesGameConfig gameConfig = HermesGameConfigParser.parse(gameProject.file("hermes.json"));
    PlatformSpec desktop = extension.getPlatforms().getDesktop();

    if (!outputDir.exists() && !outputDir.mkdirs()) {
      throw new GradleException("Could not create " + outputDir.getAbsolutePath());
    }

    Properties properties = new Properties();
    properties.setProperty("hermes.applicationClass", extension.getApplicationClass());
    properties.setProperty("hermes.debug", Boolean.toString(extension.isDebug()));
    properties.setProperty("hermes.window.width", Integer.toString(desktop.getWidth()));
    properties.setProperty("hermes.window.height", Integer.toString(desktop.getHeight()));
    properties.setProperty("hermes.window.title", desktop.getTitle());
    properties.setProperty("hermes.game.name", gameConfig.getName());
    properties.setProperty("hermes.game.scene", gameConfig.getScene());

    File file = new File(outputDir, "hermes-runtime.properties");
    try (OutputStreamWriter writer =
        new OutputStreamWriter(new FileOutputStream(file), StandardCharsets.UTF_8)) {
      properties.store(writer, "Generated by Hermes Gradle plugin");
    } catch (IOException e) {
      throw new GradleException("Failed to write hermes-runtime.properties", e);
    }
  }
}
