package dev.hermes.gradle;

import dev.hermes.tooling.config.HermesGameConfig;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.OutputStreamWriter;
import java.nio.charset.StandardCharsets;
import java.util.Properties;
import org.gradle.api.GradleException;
import org.gradle.api.Project;

/** Writes {@code hermes-runtime.properties} for packaged runtime configuration. */
final class HermesRuntimeConfigGenerator {

  private HermesRuntimeConfigGenerator() {}

  static void write(Project gameProject, HermesExtension extension, File outputDir) {
    HermesGameConfig gameConfig = HermesGameConfigs.parse(gameProject);
    DesktopPlatformSpec desktop = HermesPlatforms.resolve(gameProject).getDesktop();

    if (!outputDir.exists() && !outputDir.mkdirs()) {
      throw new GradleException("Could not create " + outputDir.getAbsolutePath());
    }

    Properties properties = new Properties();
    properties.setProperty("hermes.applicationClass", extension.getApplicationClass());
    boolean debug =
        HermesDistributionMode.isDistributionExport(gameProject) ? false : extension.isDebug();
    properties.setProperty("hermes.debug", Boolean.toString(debug));
    properties.setProperty("hermes.window.width", Integer.toString(desktop.getWidth()));
    properties.setProperty("hermes.window.height", Integer.toString(desktop.getHeight()));
    properties.setProperty("hermes.window.title", gameConfig.getTitle());
    properties.setProperty("hermes.desktop.vsync", Boolean.toString(desktop.isVsync()));
    properties.setProperty("hermes.desktop.resizable", Boolean.toString(desktop.isResizable()));
    properties.setProperty("hermes.desktop.foregroundFps", Integer.toString(desktop.getForegroundFps()));
    properties.setProperty("hermes.game.title", gameConfig.getTitle());
    properties.setProperty("hermes.game.scene", gameConfig.getScene());

    File file = new File(outputDir, "hermes-runtime.properties");
    try (OutputStreamWriter writer =
        new OutputStreamWriter(new FileOutputStream(file), StandardCharsets.UTF_8)) {
      properties.store(writer, "Generated by Hermes Gradle plugin");
    } catch (IOException e) {
      throw new GradleException("Failed to write hermes-runtime.properties", e);
    }
  }
}
